/**
 * Türkiye ilçe → şehir (il) statik eşlemesi
 * API çağrısı gerektirmez — geocoding adımını kısa devre yapar.
 * Anahtar: küçük harfli ilçe adı, Değer: resmi il adı
 */
export const DISTRICT_TO_CITY: Record<string, string> = {
  // ── İSTANBUL ──────────────────────────────────────────────────────────────
  "adalar": "İstanbul",
  "arnavutköy": "İstanbul",
  "ataşehir": "İstanbul",
  "avcılar": "İstanbul",
  "bağcılar": "İstanbul",
  "bahçelievler": "İstanbul",
  "bakırköy": "İstanbul",
  "başakşehir": "İstanbul",
  "bayrampaşa": "İstanbul",
  "beşiktaş": "İstanbul",
  "beykoz": "İstanbul",
  "beylikdüzü": "İstanbul",
  "beyoğlu": "İstanbul",
  "büyükçekmece": "İstanbul",
  "çatalca": "İstanbul",
  "çekmeköy": "İstanbul",
  "esenler": "İstanbul",
  "esenyurt": "İstanbul",
  "eyüpsultan": "İstanbul",
  "eyüp": "İstanbul",
  "fatih": "İstanbul",
  "gaziosmanpaşa": "İstanbul",
  "güngören": "İstanbul",
  "kadıköy": "İstanbul",
  "kağıthane": "İstanbul",
  "kartal": "İstanbul",
  "küçükçekmece": "İstanbul",
  "maltepe": "İstanbul",
  "pendik": "İstanbul",
  "sancaktepe": "İstanbul",
  "sarıyer": "İstanbul",
  "silivri": "İstanbul",
  "sultanbeyli": "İstanbul",
  "sultangazi": "İstanbul",
  "şile": "İstanbul",
  "şişli": "İstanbul",
  "tuzla": "İstanbul",
  "ümraniye": "İstanbul",
  "üsküdar": "İstanbul",
  "zeytinburnu": "İstanbul",

  // ── ANKARA ────────────────────────────────────────────────────────────────
  "akyurt": "Ankara",
  "altındağ": "Ankara",
  "ayaş": "Ankara",
  "bala": "Ankara",
  "beypazarı": "Ankara",
  "çamlıdere": "Ankara",
  "çankaya": "Ankara",
  "çubuk": "Ankara",
  "elmadağ": "Ankara",
  "etimesgut": "Ankara",
  "evren": "Ankara",
  "gölbaşı": "Ankara",
  "güdül": "Ankara",
  "haymana": "Ankara",
  "kahramankazan": "Ankara",
  "kalecik": "Ankara",
  "keçiören": "Ankara",
  "kızılcahamam": "Ankara",
  "mamak": "Ankara",
  "nallıhan": "Ankara",
  "polatlı": "Ankara",
  "pursaklar": "Ankara",
  "sincan": "Ankara",
  "şereflikoçhisar": "Ankara",
  "yenimahalle": "Ankara",

  // ── İZMİR ─────────────────────────────────────────────────────────────────
  "aliağa": "İzmir",
  "balçova": "İzmir",
  "bayındır": "İzmir",
  "bayraklı": "İzmir",
  "bergama": "İzmir",
  "beydağ": "İzmir",
  "bornova": "İzmir",
  "buca": "İzmir",
  "çeşme": "İzmir",
  "çiğli": "İzmir",
  "dikili": "İzmir",
  "foça": "İzmir",
  "gaziemir": "İzmir",
  "güzelbahçe": "İzmir",
  "karabağlar": "İzmir",
  "karaburun": "İzmir",
  "karşıyaka": "İzmir",
  "kemalpaşa": "İzmir",
  "kınık": "İzmir",
  "kiraz": "İzmir",
  "konak": "İzmir",
  "menderes": "İzmir",
  "menemen": "İzmir",
  "narlıdere": "İzmir",
  "ödemiş": "İzmir",
  "seferihisar": "İzmir",
  "selçuk": "İzmir",
  "tire": "İzmir",
  "torbalı": "İzmir",
  "urla": "İzmir",

  // ── MANİSA ────────────────────────────────────────────────────────────────
  "ahmetli": "Manisa",
  "akhisar": "Manisa",
  "alaşehir": "Manisa",
  "demirci": "Manisa",
  "gölmarmara": "Manisa",
  "gördes": "Manisa",
  "kırkağaç": "Manisa",
  "köprübaşı": "Manisa",
  "kula": "Manisa",
  "salihli": "Manisa",
  "sarıgöl": "Manisa",
  "saruhanlı": "Manisa",
  "selendi": "Manisa",
  "soma": "Manisa",
  "şehzadeler": "Manisa",
  "turgutlu": "Manisa",
  "yunusemre": "Manisa",

  // ── BURSA ─────────────────────────────────────────────────────────────────
  "büyükorhan": "Bursa",
  "gemlik": "Bursa",
  "gürsu": "Bursa",
  "harmancık": "Bursa",
  "İnegöl": "Bursa",
  "inegöl": "Bursa",
  "İznik": "Bursa",
  "iznik": "Bursa",
  "karacabey": "Bursa",
  "keles": "Bursa",
  "kestel": "Bursa",
  "mudanya": "Bursa",
  "mustafakemalpaşa": "Bursa",
  "nilüfer": "Bursa",
  "orhaneli": "Bursa",
  "orhangazi": "Bursa",
  "osmangazi": "Bursa",
  "yenişehir": "Bursa",
  "yıldırım": "Bursa",

  // ── ANTALYA ───────────────────────────────────────────────────────────────
  "aksu": "Antalya",
  "alanya": "Antalya",
  "akseki": "Antalya",
  "döşemealtı": "Antalya",
  "elmalı": "Antalya",
  "finike": "Antalya",
  "gazipaşa": "Antalya",
  "gündoğmuş": "Antalya",
  "ibradı": "Antalya",
  "kaş": "Antalya",
  "kemer": "Antalya",
  "kepez": "Antalya",
  "konyaaltı": "Antalya",
  "korkuteli": "Antalya",
  "kumluca": "Antalya",
  "manavgat": "Antalya",
  "muratpaşa": "Antalya",
  "serik": "Antalya",

  // ── ADANA ─────────────────────────────────────────────────────────────────
  "aladağ": "Adana",
  "ceyhan": "Adana",
  "çukurova": "Adana",
  "feke": "Adana",
  "imamoglu": "Adana",
  "karaisalı": "Adana",
  "karataş": "Adana",
  "kozan": "Adana",
  "pozantı": "Adana",
  "saimbeyli": "Adana",
  "sarıçam": "Adana",
  "seyhan": "Adana",
  "tufanbeyli": "Adana",
  "yumurtalık": "Adana",
  "yüreğir": "Adana",

  // ── KONYA ─────────────────────────────────────────────────────────────────
  "akören": "Konya",
  "akşehir": "Konya",
  "altınekin": "Konya",
  "beyşehir": "Konya",
  "bozkır": "Konya",
  "cihanbeyli": "Konya",
  "çeltik": "Konya",
  "çumra": "Konya",
  "derbent": "Konya",
  "derebucak": "Konya",
  "doğanhisar": "Konya",
  "emirgazi": "Konya",
  "ereğli": "Konya",
  "güneysinir": "Konya",
  "hadim": "Konya",
  "halkapınar": "Konya",
  "hüyük": "Konya",
  "ilgın": "Konya",
  "kadınhanı": "Konya",
  "karapınar": "Konya",
  "karatay": "Konya",
  "kulu": "Konya",
  "meram": "Konya",
  "sarayönü": "Konya",
  "selçuklu": "Konya",
  "seydişehir": "Konya",
  "taşkent": "Konya",
  "tuzlukçu": "Konya",
  "yalıhüyük": "Konya",
  "yunak": "Konya",

  // ── KOCAELI ───────────────────────────────────────────────────────────────
  "başiskele": "Kocaeli",
  "çayırova": "Kocaeli",
  "darıca": "Kocaeli",
  "derince": "Kocaeli",
  "dilovası": "Kocaeli",
  "gebze": "Kocaeli",
  "gölcük": "Kocaeli",
  "izmit": "Kocaeli",
  "kandıra": "Kocaeli",
  "karamürsel": "Kocaeli",
  "kartepe": "Kocaeli",
  "körfez": "Kocaeli",
  "İzmit": "Kocaeli",

  // ── MERSİN ────────────────────────────────────────────────────────────────
  "akdeniz": "Mersin",
  "anamur": "Mersin",
  "aydıncık": "Mersin",
  "bozyazı": "Mersin",
  "çamlıyayla": "Mersin",
  "erdemli": "Mersin",
  "gülnar": "Mersin",
  "mezitli": "Mersin",
  "mut": "Mersin",
  "silifke": "Mersin",
  "tarsus": "Mersin",
  "toroslar": "Mersin",
  // yenişehir (Mersin) — Bursa ile çakışıyor, DB lookup öncelikli

  // ── GAZİANTEP ─────────────────────────────────────────────────────────────
  "araban": "Gaziantep",
  "islahiye": "Gaziantep",
  "karkamış": "Gaziantep",
  "nizip": "Gaziantep",
  "nurdağı": "Gaziantep",
  "oğuzeli": "Gaziantep",
  "şahinbey": "Gaziantep",
  "şehitkamil": "Gaziantep",
  "yavuzeli": "Gaziantep",

  // ── TRABZON ───────────────────────────────────────────────────────────────
  "akçaabat": "Trabzon",
  "araklı": "Trabzon",
  "arsin": "Trabzon",
  "beşikdüzü": "Trabzon",
  "çarşıbaşı": "Trabzon",
  "çaykara": "Trabzon",
  "dernekpazarı": "Trabzon",
  "düzköy": "Trabzon",
  "hayrat": "Trabzon",
  "köprübaşı trabzon": "Trabzon",
  "maçka": "Trabzon",
  "of": "Trabzon",
  "ortahisar": "Trabzon",
  "sürmene": "Trabzon",
  "şalpazarı": "Trabzon",
  "tonya": "Trabzon",
  "vakfıkebir": "Trabzon",
  "yomra": "Trabzon",

  // ── SAKARYA ───────────────────────────────────────────────────────────────
  "adapazarı": "Sakarya",
  "akyazı": "Sakarya",
  "arifiye": "Sakarya",
  "erenler": "Sakarya",
  "ferizli": "Sakarya",
  "geyve": "Sakarya",
  "hendek": "Sakarya",
  "karapürçek": "Sakarya",
  "karasu": "Sakarya",
  "kaynarca": "Sakarya",
  "kocaali": "Sakarya",
  "mithatpaşa": "Sakarya",
  "pamukova": "Sakarya",
  "sapanca": "Sakarya",
  "serdivan": "Sakarya",
  "söğütlü": "Sakarya",
  "taraklı": "Sakarya",
};

/**
 * Türkçe harfleri normalize eder — JavaScript'in toLowerCase() hatası:
 * "İ".toLowerCase() → "i̇" (2 karakter) değil, "i" (1 karakter) olmalı.
 */
export function trLower(s: string): string {
  return s
    .replace(/İ/g, "i")
    .replace(/I/g, "ı")
    .replace(/Ğ/g, "ğ")
    .replace(/Ü/g, "ü")
    .replace(/Ş/g, "ş")
    .replace(/Ö/g, "ö")
    .replace(/Ç/g, "ç")
    .toLowerCase();
}

/**
 * İlçe adından il (şehir) adını döndürür.
 * Türkçe büyük/küçük harf farkını doğru işler.
 * @param districtName - İlçe adı (herhangi bir harf büyüklüğünde)
 * @returns İl adı ya da null (bilinmiyorsa)
 */
export function getCityForDistrict(districtName: string): string | null {
  if (!districtName) return null;
  return DISTRICT_TO_CITY[trLower(districtName)] ?? null;
}
